# Generated by Django 4.1.4 on 2022-12-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
