# Generated by Django 4.1.4 on 2022-12-23 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innerpage', '0002_alter_privacypolicy_options_privacypolicy_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
