# Generated by Django 4.1.4 on 2022-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_whyus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyus',
            options={'ordering': ['number'], 'verbose_name_plural': 'Why us'},
        ),
        migrations.AddField(
            model_name='whyus',
            name='short_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
