# Generated by Django 4.1.4 on 2022-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_whyus_options_whyus_short_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brief_description', models.TextField()),
                ('real_description', models.TextField()),
                ('special_image', models.ImageField(upload_to='specials')),
            ],
        ),
    ]
