# Generated by Django 4.1.4 on 2022-12-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Staff member name')),
                ('position', models.CharField(max_length=100)),
                ('twitter', models.URLField(verbose_name='Twitter link')),
                ('facebook', models.URLField(verbose_name='Facebook link')),
                ('instagram', models.URLField(verbose_name='Instagram link')),
                ('photo', models.ImageField(upload_to='', verbose_name='Employee photo')),
            ],
        ),
    ]
