# Generated by Django 4.1.4 on 2022-12-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram link'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, help_text='600x600px images recomended', null=True, upload_to='staff', verbose_name='Employee photo'),
        ),
    ]
