# Generated by Django 4.1.4 on 2022-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_gallery_options_gallery_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Full name')),
                ('job', models.CharField(max_length=30, verbose_name='Job')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials')),
                ('testimonial', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order'], 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
