# Generated by Django 4.1.4 on 2022-12-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_whyus_submit_alter_gallery_image_alter_gallery_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whyus',
            old_name='submit',
            new_name='created',
        ),
        migrations.AddField(
            model_name='about',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
