# Generated by Django 4.1.4 on 2022-12-24 14:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_submit_whyus_created_about_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70, verbose_name='City / Location')),
                ('opentime', models.CharField(max_length=50, verbose_name='Open hours')),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=30, verbose_name='Phone number')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.about_upload_to),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to=core.models.event_upload_to, verbose_name='Event image'),
        ),
    ]
