# Generated by Django 4.1.4 on 2022-12-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contact_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='special_number',
            field=models.IntegerField(default=0),
        ),
    ]
