# Generated by Django 4.1.4 on 2022-12-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_special_special_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='special_number',
        ),
        migrations.AddField(
            model_name='special',
            name='tab',
            field=models.CharField(help_text='Following this pattern: #tab-number', max_length=10, null=True),
        ),
    ]
