# Generated by Django 4.1.4 on 2022-12-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_brief_description_special_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='image1',
            field=models.ImageField(null=True, upload_to='specials', verbose_name='Image Special 1'),
        ),
        migrations.AddField(
            model_name='special',
            name='image2',
            field=models.ImageField(null=True, upload_to='specials', verbose_name='Image Special 2'),
        ),
        migrations.AddField(
            model_name='special',
            name='image3',
            field=models.ImageField(null=True, upload_to='specials', verbose_name='Image Special 3'),
        ),
        migrations.AddField(
            model_name='special',
            name='image4',
            field=models.ImageField(null=True, upload_to='specials', verbose_name='Image Special 4'),
        ),
        migrations.AddField(
            model_name='special',
            name='image5',
            field=models.ImageField(null=True, upload_to='specials', verbose_name='Image Special 5'),
        ),
        migrations.AlterField(
            model_name='special',
            name='special4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Special 4 (optional)'),
        ),
        migrations.AlterField(
            model_name='special',
            name='special5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Special 5 (optional)'),
        ),
    ]
