# Generated by Django 4.1.4 on 2022-12-27 13:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_special_image1_special_image2_special_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='image1',
            field=models.ImageField(null=True, upload_to=core.models.special1_upload_to, verbose_name='Image Special 1'),
        ),
        migrations.AlterField(
            model_name='special',
            name='image2',
            field=models.ImageField(null=True, upload_to=core.models.special2_upload_to, verbose_name='Image Special 2'),
        ),
        migrations.AlterField(
            model_name='special',
            name='image3',
            field=models.ImageField(null=True, upload_to=core.models.special3_upload_to, verbose_name='Image Special 3'),
        ),
        migrations.AlterField(
            model_name='special',
            name='image4',
            field=models.ImageField(null=True, upload_to=core.models.special4_upload_to, verbose_name='Image Special 4'),
        ),
        migrations.AlterField(
            model_name='special',
            name='image5',
            field=models.ImageField(null=True, upload_to=core.models.special5_upload_to, verbose_name='Image Special 5'),
        ),
    ]
